# From https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-context
---
name: (Dev only) Diagnostics
on:
  #push: {}
  pull_request_target:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_removed
  #pull_request:
  #  types:
  #    - assigned
  #    - unassigned
  #    - labeled
  #    - unlabeled
  #    - opened
  #    - edited
  #    - closed
  #    - reopened
  #    - synchronize
  #    - ready_for_review
  #    - locked
  #    - unlocked
  #    - review_requested
  #    - review_request_removed

env:
  GITLAB_SERVER_URL: ${{ secrets.GITLAB_SERVER_URL }} # https://gitlab.com
  GITLAB_API_URL: ${{ secrets.GITLAB_API_URL }}       # https://gitlab.com/api/v4
  GITLAB_ORG: ${{ github.event.organization.login }}
  PUPPET_VERSION: '~> 6'

jobs:
  contexts:
    name: 'Examine Context contents'
    runs-on: ubuntu-latest.04
    steps:
      - name: Dump contexts
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Dump env context
        env:
          ENV_CONTEXT: ${{ toJson(env) }}
        run: echo "$ENV_CONTEXT"
      - name: Dump env vars
        run: env | sort
