---
name: Verify Action
on:
  push:
    branches:
      - main
      - releases/*
      - tests/*

jobs:
  test_glci_syntax_defaults:
    name: Test action (with defaults)
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: simp/github-action-gitlab-ci-syntax-check@tests/fix-gitlab-api

  test_glci_syntax_api_url:
    name: Test action (with API url)
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: simp/github-action-gitlab-ci-syntax-check@tests/fix-gitlab-api
        with:
          gitlab_api_url:  '${{ vars.GITLAB_API_URL }}/projects/simp%2Fsimp-core'

  test_glci_syntax_token:
    name: Test action with TOKEN
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: simp/github-action-gitlab-ci-syntax-check@tests/fix-gitlab-api
        with:
          gitlab_api_private_token: ${{ secrets.GITLAB_API_PRIVATE_TOKEN }}

  test_glci_syntax_api_full:
    name: Test action (given gitlab ci token + API url)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: simp/github-action-gitlab-ci-syntax-check@tests/fix-gitlab-api
        with:
          gitlab_api_url:  '${{ vars.GITLAB_API_URL }}/projects/simp%2Fsimp-core'
          gitlab_api_private_token: ${{ secrets.GITLAB_API_PRIVATE_TOKEN }}

